apiVersion: v1
kind: ConfigMap
metadata:
  name: demand-forecast-config
data:
  mlflow_tracking_uri: "http://mlflow.mlflow.svc.cluster.local:5000"
  redis_host: "redis.demand-forecast.svc.cluster.local"
  redis_port: "6379"